project:
  type: website
  output-dir: _site
  render:
    - index.qmd

website:
  title: "Todos os caminhos levam a Roma"
  description: "Passeio aleatório de um Estatístico"
  site-url: ""

format:
  revealjs:
    theme: default
    css: [css/sfah.css, css/fonts.css]
    slide-number: true
    transition: fade
    revealjs-options:
      width: 1600
      height: 900
      margin: 0.1
      minScale: 0.7
      maxScale: 1.0
